apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: flux-dummy
  namespace: vqy364-test2
spec:
  chart: flux-dummy
  version: 1.0.x
  sourceRef:
    name: flux-dummy
    kind: HelmRepository
  interval: 2m
