apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-dummy
  namespace: vqy364-test2
spec:
  chart:
    spec:
      chart: flux-dummy
      sourceRef:
        kind: HelmChart
        name: flux-dummy
  interval: 1m0s
